use_frameworks!

platform :ios, '10.0'

target 'VSwitch_Example' do
  pod 'VSwitch', :path => '../'
  pod 'SnapKit'
  pod 'SwifterSwift'
  target 'VSwitch_Tests' do
    inherit! :search_paths

    
  end
end
